const A2012to2013=['Lupe Fiasco','Hot Chelle Rae','Big Sean','Gotye','Carly Rae Jepsen','Fun','Janelle Monáe','One Direction','2 Chainz','Imagine Dragons','Miguel','Linkin Park','Baauer','Ryan Lewis','Nate Ruess','Daft Punk','Pharrell Williams','Lorde','Avicii','Anna Kendrick','Zedd','Sweedish House Mafia','Charli XCX','Capital Cities','Mac Miller','Majid Jordan','Lana Del Ray','Psy','Calvin Harris','Luke Bryan','Tove Lo','Ed Sheeran','Olly Murs','Emeli Sande','Ace Hood','Florida Georgia Line']
const A2014to2016=['John Legend','Rude','Meghan Trainor','Iggy Azalea','Bastille','Sia','Disclosure','Clean Bandit','Jess Glyne','Aloe Blacc','Coldplay','Bobby Shmurda','Tinashe','Becky G','Rich Homie Quan','Shakira','T.I','Mike Will Made-It','ScHoolboy Q','Mark Ronson','Charlie Puth','Hozier','The Weeknd','Kendrick Lamar','Major Lazer','Skrillex','DJ Snake','MØ','Fetty Wap','Fifth Harmony','Jhenė Aiko','ASAP Rocky','Bebe Rexha','Shawn Mendes','Sam Hunt','X Ambassadors','Nick Jonas','Jidenna','Nicky Jam','Wizkid','Kyla','Desiigner','The Chainsmokers','Lucas Graham','G-Eazy','Twenty One Pilots','Zayn','Bryson Tiller','Alessia Cara','MNEK','Kelvin Gates','Post Malone','Travis Scott','French Montana','Young Dolph']

const realNames=['Kesha','Train','Katy Perry','Snoop Dog','Usher','B.o.B','Hayley Williams','will.i.am','Eminem','Rihanna','Bruno Mars','Young Money','Jason Derulo','Lady Gaga','Beyoncé','Mike Posner','The Black Eyed Peas','Jay-Z','Alicia Keys','Pitbull','Travie McCoy','Drake','Nelly','Ludacris','Timbaland','Justin Timberlake','Maroon 5','Flo Rida','David Guetta','Michael Bublé','Lil Wayne','Justin Bieber','Adam Lambert','Taylor Swift','Jeezy','Trey Songz','Sean Paul','Lil Jon','Nicki Minaj','Miley Cyrus','Chris Brown','Tyga','Kevin McCall','Britney Spears','Shontelle','Kanye West','Kelly Clarkson','OneRepublic'
,'Selena Gomez','DJ Khalid','T-Pain','Wiz Khalifa','Rick Ross','Birdman','Piles','Carrie Underwood','Adele',
'Sean Kingston','The Band Perry','LMFAO','Lauren Bennett','CeeLo Green','Christina Aguilera','Jennifer Lopez','Enrique Iglesias','Pink','Jeremih','50 Cent','Diddy','Skyla Grey','Busta Rhymes','Wale','Waka Floka Flame','Avril Lavigne','Luke Bryan','The Script',
'Ne-Yo','Afrojack','Foster The People','Lady Antebellum','Taio Cruz','Lloyd','Iyaz','Owl City','La Roux','Kris Allen','3OH!3','Orianthi','Ray J',...A2012to2013,...A2014to2016]


export default realNames